# Generated by Django 4.0.5 on 2022-08-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='smartphone.jpg', upload_to='media/'),
        ),
    ]
