# Generated by Django 4.0.5 on 2022-08-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='media/smartphone.jpg', upload_to='blog/media/'),
        ),
    ]
