# Generated by Django 4.0.5 on 2022-08-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='smartphone.jpg', upload_to=''),
        ),
    ]
